myproject/marketplace/urls.py
from django.urls import path
from .views import client, order, products, client_list, upload_product

urlpatterns = [
    path('client/', client, name='client'),
    path('order/', order, name='order'),
    path('product/', products, name='products'),
    path('clients/', client_list, name='client_list'),
    path('media/', upload_product, name='upload_product')
]

myproject/myapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('', include('marketplace.urls')),
    #path('debug/', include('debug_toolbar.urls')),
]

myproject/marketplace/models.py
from django.db import models



class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    registration_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Клиент(ы): {self.name}' '-' f'Номер: {self.phone_number}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    date_added = models.DateField(auto_now_add=True)
    photo = models.ImageField(upload_to='media/')

    def __str__(self):
        return f'Продукт(ы): {self.name}' '-' f'Цена: {self.price}' '-' f'Описание: {self.description}'


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    order_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Заказ(ы): {self.total_amount}' '-' f'Клиент(ы): {self.client.name}' '-' f' Дата: {self.order_date}'

myproject/myapp/models.py
from django.db import models

myproject/myapp2/models.py
from django.db import models


class GameModel(models.Model):
    result = models.CharField(max_length=10)
    played = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Результат игры: {self.result}, время: {self.played}'

myproject/marketplace/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'quantity', 'photo']

    photo = forms.ImageField()

myproject/marketplace/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponse
from django.views.generic import TemplateView
from marketplace.models import Client, Product, Order
from django.db.models import Sum


def client(request):
    res = Client.objects.all()
    res1 = ''
    for i in res:
        res1 += str(i) + '<br>'
    return HttpResponse(f'{res1}')


def products(request):
    products = Product.objects.all()
    r = ''
    for i in products:
        r += str(i) + '<br>'
    return HttpResponse(f'{r}')


def order(request):
    order = Order.objects.all()
    r = ''
    for i in order:
        r += str(i) + '<br>'
    return HttpResponse(f'{r}')


def client_list(request):
    clients = Client.objects.all()
    orders = Order.objects.all
    context = {
        'clients': clients,
        'orders': orders,
    }
    return render(request, 'orders_list.html', context)


def upload_product(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'upload_product.html', context)

myproject/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
import logging

logger = logging.getLogger(__name__)


def main(request):
    logger.info('Index page accessed')
    res = """
        <h1>Добро пожаловать на мой первый Django-сайт!</h1>
        <p>Привет! Я - Александр!</p>
        """
    logging.info('Пользователь посетил главную страницу')
    return HttpResponse(res)


def about(request):
    res = """
        <h1>Обо мне</h1>
        <p>Привет! Меня зовут Алексанр и я начинающий Python-разработчик.</p>
        """
    logging.info('Пользователь посетил страницу "О себе"')
    return HttpResponse(res)

myproject/myapp2/views.py
from django.shortcuts import render

# Create your views here.

myproject/marketplace/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Блог {% endblock %}</title>
</head>
<body>
{% block content %}
Контент скоро появится...
{% endblock %}
</body>
</html>

myproject/marketplace/templates/client_order.html
{% extends 'base.html' %}

{% block content %}
 <title>Список клиентов</title>
</head>
<body>
    <h1>Список клиентов</h1>
    <ul>
    {% for client in clients %}
        <li><a href="{% url 'client_orders' client.id %}">{{ client.name }}</a></li>
    {% endfor %}
    </ul>

    <h2>Заказы клиента</h2>
    <ul>
    {% for order in orders %}
        <li>{{ order.name }}</li>
    {% endfor %}
    </ul>
{% endblock %}

myproject/marketplace/templates/clients.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

myproject/marketplace/templates/orders_list.html
{% extends 'base.html' %}

{% block content %}
<title>Список клиентов и их заказы</title>
</head>
<body>
<h1>Список клиентов и их заказы</h1>

{% if clients %}
<ul>
    {% for client in clients %}
    <li>
        <h2>{{ client.name }}</h2>
        <ul>
            {% for order in client.order_set.all %}
            <li>
                Заказ #{{ order.id }} - {{ order.order_date }}:
                Общая сумма: {{ order.total_amount }}
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Нет доступных клиентов.</p>
{% endif %}
{% endblock %}

myproject/marketplace/templates/upload_product.html
{% extends 'base.html' %}

{% block content %}


<title>Загрузка фото</title>
</head>
<body>
<h1>Загрузка фото</h1>

<form action="/upload/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="photo">
    <input type="submit" value="Загрузить">
</form>


{% endblock %}